services:
  homepage:
    build: .
    ports:
      - "5000:4000"
    pid: host
    volumes:
      - /sys:/sys:ro
      - /:/hostfs:ro
      - ./data/services.json:/app/data/services.json
    environment:
      - HOST_FS=/hostfs
      - ICAL_URL=${ICAL_URL}
    restart: unless-stopped
